Update API docs.
scramjetorg/transform-hub pull request #130
Opened 2021-10-29 17:13 UTC by agne6ka

Ticket: https://app.asana.com/0/1201235440001052/1201264543489281

2021-11-03 14:23 UTC, patuwwy commented on docs/API-reference.md
> +    <strong>[ GET ]</strong> <code>/api/v1/instances/</code> <small>- list all instances</small>
please remove trailing slash

2021-11-03 14:25 UTC, patuwwy commented on docs/API-reference.md
> +    <strong>[ GET ]</strong>  <code>/api/v1/stream/log</code> <small>- stream all host logs</small>
`/api/v1/stream/log`

2021-11-03 14:27 UTC, patuwwy commented on docs/API-reference.md
> +- GET /api/v1/stream/stdout​
- POST /api/v1/instance/:xx/stdin​
- GET /api/v1/instance/:xx/stderr
- GET /api/v1/instance/:xx/stdout

2021-11-03 14:28 UTC, patuwwy requested changes
see comments

2021-11-15 15:09 UTC, a-tylenda commented on docs/API-reference.md
> +<br> <strong>**Parameters**</strong>
endpoint /health has no parameters

2021-11-16 09:20 UTC, alicja-gruzdz commented on docs/API-reference.md
> +<br> <strong>**Parameters**</strong>
thanks Aga, I will correct it.

2021-11-20 21:37 UTC, MichalCz commented
Aga, let's add the "official quick install guide" at top of readme, before the install from repo one-liner.

Something like this:

* Install node.js v16.x [for instance from nodesource](https://github.com/nodesource/distributions/blob/master/README.md)
* Install docker [for instance via get-docker](https://github.com/docker/docker-install/blob/master/README.md) - ideally we'll add `(optionally)` here when @pietrzakacper is done.
* Install STH from repo:

```sh
npm i -g @scramjet/sth
```

* Start STH:

```sh
transform-hub
```

2021-11-23 10:40 UTC, alicja-gruzdz commented
> Aga, let's add the "official quick install guide" at top of readme, before the install from repo one-liner.
> 
> Something like this:
> 
> * Install node.js v16.x [for instance from nodesource](https://github.com/nodesource/distributions/blob/master/README.md)
> * Install docker [for instance via get-docker](https://github.com/docker/docker-install/blob/master/README.md) - ideally we'll add `(optionally)` here when @pietrzakacper is done.
> * Install STH from repo:
> 
> ```shell
> npm i -g @scramjet/sth
> ```
> 
> * Start STH:
> 
> ```shell
> scramjet-transform-hub
> ```

thanks :) @a-tylenda is adding it in https://github.com/scramjetorg/transform-hub/pull/137

2021-11-23 11:03 UTC, a-tylenda commented on packages/cli/src/lib/commands/host.ts
> +    * Show whole logs form host
```suggestion
    * Show whole logs from host
```

2021-11-23 11:05 UTC, a-tylenda commented on packages/cli/src/bin/index.ts
> +     * host [command]                something
```suggestion
     * host [command]                operations on host
```

2021-11-23 11:06 UTC, a-tylenda commented on packages/cli/src/lib/commands/host.ts
> +    * Get STH version number form package.json file
```suggestion
    * Get STH version number from package.json file
```

2021-11-23 11:08 UTC, a-tylenda commented on packages/cli/src/lib/output.ts
> + * Command form commander contains obj with whole params, that user provide to the console.
```suggestion
 * Command from commander contains obj with whole params, that user provides to the console.
```

2021-11-23 11:22 UTC, a-tylenda approved these changes

2021-11-23 13:11 UTC, agne6ka commented on docs/API-reference.md
> +- GET /api/v1/stream/stdout​
Done

2021-11-23 13:13 UTC, patuwwy approved these changes

2021-11-23 13:13 UTC, merged