[WIP] Complete the general documentation in STH
scramjetorg/transform-hub pull request #137
Opened 2021-11-17 18:23 UTC by a-tylenda

2021-11-23 11:18 UTC, alicja-gruzdz approved these changes

2021-11-24 08:54 UTC, patuwwy approved these changes

2021-11-24 08:56 UTC, agne6ka requested changes

2021-11-24 09:02 UTC, agne6ka requested changes

2021-11-24 09:02 UTC, agne6ka commented on README.md
>  * You can see the [Scramjet Transform Hub API docs here](./docs/development-guide/stream-and-api.md)
```suggestion
* You can see the [Scramjet Transform Hub API docs here](./docs/interfaces/API-reference.md)
```

2021-11-24 10:59 UTC, agne6ka approved these changes

2021-11-24 11:28 UTC, merged