Introduce: si seq prune
scramjetorg/transform-hub pull request #425
Opened 2022-04-12 07:59 UTC by MichalCz

There's not much to it. Upload a couple sequences and then:

```sh
si seq ls
si seq prune
si seq ls
```﻿

The second `ls` should show... no sequences? :)

2022-04-12 08:09 UTC, ErykSol requested changes

2022-04-12 09:00 UTC, ErykSol requested changes

2022-04-12 09:00 UTC, ErykSol commented on packages/cli/src/lib/commands/sequence.ts
> +    sequenceCmd
At the end of this file is already prepared command for prune in developer mode- this should be moved down and merged with that one (remove developer flag)  to keep proper command order.

2022-04-12 09:31 UTC, ErykSol approved these changes

2022-04-12 09:32 UTC, a-tylenda commented on packages/cli/src/lib/commands/sequence.ts
> +        .command("prune")
```suggestion
        .command("prune")
        .description("delete multiple sequences on actual selected hub")
```

2022-04-12 10:04 UTC, a-tylenda commented
Verification failed during command execution: `si seq prune --force`.
**Steps to Reproduce**
1. start sth: `scramjet-transform-hub`
2. send a few Sequences to STH, start the last one: `si seq start -`
3. force prune to delete all Sequences including the one which is running: `si seq prune --force`

Screenshot of error I received:

![image](https://user-images.githubusercontent.com/61054769/162934470-d60c627c-c266-447a-b666-8a882198729e.png)

I think that there is not enough time for the Sequence to stop working after "kill" is sent. DELETE request is sent while killing process is not finished.

2022-04-12 10:16 UTC, a-tylenda commented on packages/cli/src/lib/commands/sequence.ts
> +                            return getInstance(id).kill();
```suggestion
                            return getInstance(id).kill();
                            defer(1000);
```

maybe we could give some time for Sequence to stop working?

2022-04-12 13:55 UTC, a-tylenda commented on packages/cli/src/lib/commands/sequence.ts
> +        .option("-f,--force", "Removes also active sequences")
```suggestion
        .option("-f,--force", "Removes also active sequences")
        .description("remove all Sequences from the current scope (use with caution)")
        
```

2022-04-13 12:44 UTC, a-tylenda commented
verification complete:

![image](https://user-images.githubusercontent.com/61054769/163182708-d3cf7817-ec80-4e27-8d76-d043703c44b3.png)

2022-04-13 13:16 UTC, merged