Add message about beta
scramjetorg/transform-hub pull request #469
Opened 2022-04-26 13:46 UTC by MichalCz

This adds a small log file to let users know that they can
now enrol to the waiting list for our Beta platform.﻿

2022-04-26 14:24 UTC, bizconnectme requested changes
Add better marketing infos

2022-04-26 14:25 UTC, bizconnectme requested changes
New tips

2022-04-26 15:40 UTC, alicja-gruzdz approved these changes
It's a subtle banner.

It's a matter of personal taste but I prefer the message to be printed together with extra.
Also, without diving the sentence.


Verified :heavy_check_mark: 
![Zrzut ekranu z 2022-04-26 17-16-46](https://user-images.githubusercontent.com/8177865/165338483-0a23df3f-c743-49f4-9d78-83de2bc9d49d.png)

2022-04-27 08:26 UTC, a-tylenda commented on packages/sth/src/bin/hub.ts
> +];
```suggestion
const tips = [
    ["Run Sequences in our cloud.", { "Check it": "out as a beta tester", here: "https://scr.je/join-beta-sth" }],
    ["Now you can run Sequences in the cloud and deploy them to multiple locations simultaneously", { "check the": "beta version", "at-this-link": "https://scr.je/join-beta-sth" }],
    ["You don't need to maintain your own server anymore", { "Check out": "Scramjet Cloud Platform", here: "https://scr.je/join-beta-sth" }]
];
```

2022-04-28 09:55 UTC, a-tylenda approved these changes

2022-04-28 09:56 UTC, merged