Test commit
scramjetorg/transform-hub pull request #530
Opened 2022-05-30 14:29 UTC by Tatarinho

2022-06-01 06:54 UTC, Tatarinho commented on package.json
> +    "copy:packages": "mkdir -p test/js test/python && cp -R ../reference-apps/js/*.tar.gz test/js && cp -R ../reference-apps/python/*.tar.gz test/python",
Good eye, I fixed it.

2022-06-02 08:55 UTC, MichalCz approved these changes

2022-06-02 09:01 UTC, MichalCz requested changes
We need to add new tests to workflows.

2022-06-02 09:16 UTC, jan-warchol commented
> We need to add new tests to workflows.

done.

2022-06-02 10:40 UTC, MichalCz approved these changes

2022-06-02 10:41 UTC, merged