Tag docker images with commit, don't overwrite release tag
scramjetorg/transform-hub pull request #539
Opened 2022-06-02 11:17 UTC by jan-warchol

**What?**  
Do not "reuse" docker tags, especially release tags. Tag images with human-readable combination of most recent tag and current commit ID.

**Why?**  
Once a "release" tag (like 0.24.1) is used on an image, it should never
be used on other images to avoid confusion and wrong deployments.
Using a commit ID to tag images will make it easy to refer to specific images elsewhere.

**Usage:**

Running `yarn build:docker` e.g. in runner package should result in something like
```
...
Successfully tagged scramjetorg/runner:v0.24.1-8-g8a836382-dirty
```
Indicating it was done on commit 8a836382, with uncommitted changes to the files.

2022-06-02 12:47 UTC, daro1337 commented
It's not gonna work since test has `hardcoded` docker images
What u're doing:
- create docker image `runner-py:<commitID>`
- upload as artifact
- download artifact and load to docker daemon  `runner-py:<commitID>`
- but test launching `scramjetorg\runner-py:<version>`

proof: https://github.com/scramjetorg/transform-hub/runs/6707775026?check_suite_focus=true#step:14:60

That means all test from this commit was on released version

This leads to no testing for changes from PR

2022-06-02 12:49 UTC, daro1337 requested changes
It's not gonna work since test has hardcoded docker images
What u're doing:

    create docker image runner-py:<commitID>
    upload as artifact
    download artifact and load to docker daemon runner-py:<commitID>
    but test launching scramjetorg\runner-py:<version>

proof: https://github.com/scramjetorg/transform-hub/runs/6707775026?check_suite_focus=true#step:14:60

That means all tests from this commit was on already released version

This leads to no testing  changes from PRs

2022-06-02 15:53 UTC, patuwwy approved these changes

2022-06-02 17:16 UTC, MichalCz commented
Please check (and confirm):

[ ] if there's no documentation that needs changes? 
[ ] Are all scripts working with this?
[ ] Won't this affect the *other* project?

2022-06-02 20:58 UTC, stokowski commented
Maybe switch to short commit-ids: `git rev-parse --short HEAD` ?

2022-06-02 20:59 UTC, stokowski approved these changes
lgtm

2022-06-03 08:20 UTC, jan-warchol commented
> Please check (and confirm):
> 
> [ ] if there's no documentation that needs changes?

I've searched STH readme and docs repo, didn't find anything. Also, the tests will use default images (i.e. from release) if not told otherwise.

> [ ] Are all scripts working with this?

The only scripts concerned with docker that I found are `test:docker` in pre-runner and runner. They don't seem affected - they crash in the same way as they crash on devel :p I suppose they are not used.

> [ ] Won't this affect the _other_ project?

I've run [compatibility tests](https://github.com/scramjetorg/platform-tests/actions/runs/2433145215) and triggered CPM [CI build](https://github.com/scramjetorg/scramjet-cpm-dev/runs/6722217582?check_suite_focus=true) which is all green.

Interestingly, the CPM build failed [the first time](https://github.com/scramjetorg/scramjet-cpm-dev/runs/6721784955?check_suite_focus=true), but I'm pretty sure the failure is not related: no errors about images, it didn't fail on starting a sequence. In fact, the data [seems to have been produced](https://github.com/scramjetorg/scramjet-cpm-dev/runs/6721784955?check_suite_focus=true#step:34:17228), so it seems like a flaky test.

2022-06-03 08:24 UTC, MichalCz approved these changes

2022-06-03 08:34 UTC, daro1337 commented on packages/pre-runner/package.json
>      "clean:docker": "docker rm -f scramjetorg/pre-runner; docker volume rm scramjetorg/prerunner-$(git rev-parse --short HEAD)",
```suggestion
    "clean:docker": "docker rm -f scramjetorg/pre-runner; docker volume rm scramjetorg/prerunner-$(git rev-parse HEAD)",
```

2022-06-03 08:34 UTC, daro1337 commented on packages/runner/package.json
>      "clean:docker": "docker rm -f runner; docker volume rm prerunner-$(git rev-parse --short HEAD)"
```suggestion
    "clean:docker": "docker rm -f runner; docker volume rm prerunner-$(git rev-parse HEAD)"
```

2022-06-03 09:16 UTC, daro1337 approved these changes

2022-06-03 09:25 UTC, merged