Decouple last remaining refapps
scramjetorg/transform-hub pull request #580
Opened 2022-06-29 10:12 UTC by Tatarinho

2022-07-06 10:35 UTC, patuwwy commented on bdd/features/e2e/E2E-010-cli.feature
> +    @remove
why `remove`? There are some sample sequences in `bdd/data/sequences` directory we can use to test `pack`

2022-07-06 10:38 UTC, patuwwy requested changes
Please rebase, there are changes introduced in this part of code unifying CLI wording and steps

2022-07-07 08:38 UTC, a-tylenda approved these changes

2022-07-07 08:49 UTC, patuwwy approved these changes

2022-07-07 08:50 UTC, merged