Fix si seq send does not return valid exit codes
scramjetorg/transform-hub pull request #631
Opened 2022-08-09 09:40 UTC by Tatarinho

Steps to Reproduce:

```
yarn start:dev:cli seq send simple-counter-js.tar.gz; echo $?
yarn run v1.22.19
$ ts-node packages/cli/src/bin/index.ts seq send simple-counter-js.tar.gz
Error: File "simple-counter-js.tar.gz" not found.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
1
```

2022-08-09 09:46 UTC, patuwwy commented
IMO we should introduce actionSafeHandler method and use it for all `si` commands

2022-08-09 10:07 UTC, daro1337 requested changes
This only handle `file not found error` what with other errors?
 
```
Expected behavior
Any error from CLI should return exit code != 0
```

2022-08-11 15:16 UTC, patuwwy requested changes
should catch all exceptions

2022-09-01 12:34 UTC, patuwwy commented
Replaced with #665

2022-09-01 12:34 UTC, closed without merging