Add missing commands to the start snippet
scramjetorg/transform-hub pull request #636
Opened 2022-08-10 22:20 UTC by patuwwy

**How it works:**

-
-
-

**Review checks:**

These aspects need to be checked by the reviewer:

- [ ] Verify and confirm operation (please post a screenshot) 
- [ ] All STH tests pass
- [ ] All [Scramjet Cloud Platform](https://docs.scramjet.org/platform) tests pass
- [ ] Documentation is updated or no changes

2022-08-10 22:24 UTC, patuwwy commented
this snippet still needs rework. Why?
```
$ SEQ_ID=$(si seq send ./package.tar.gz)
Request ok: http://127.0.0.1:8000/api/v1/sequence status: 200 OK
$ echo $SEQ_ID
SequenceClient { _id: 'c9ab1abf-5a5e-49b3-9a89-24c35fab06ec', host: HostClient { apiBase: 'http://127.0.0.1:8000/api/v1', client: ClientUtils { apiBase: 'http://127.0.0.1:8000/api/v1', fetch: [Function (anonymous)], normalizeUrlFn: [Function: normalizeUrl], log: [Object] } }, sequenceURL: 'sequence/c9ab1abf-5a5e-49b3-9a89-24c35fab06ec' }
```

default format for cli is pretty https://github.com/scramjetorg/transform-hub/blob/devel/packages/cli/src/lib/config.ts#L149

2022-08-10 22:27 UTC, patuwwy commented
Apart from that we can show `si seq deploy` version

2022-08-12 07:50 UTC, a-tylenda commented on packages/sth/README.md
> +si seq pack . -o ~/package.tar.gz              # compress the app to a package
These changes must be implemented in `readme.mtpl` file → packages/sth/src/readme.mtpl

2022-08-12 07:54 UTC, a-tylenda requested changes
Changes should be added in `readme.mtpl` instead of `readme.md`

2022-08-16 08:50 UTC, alicja-gruzdz commented
That's a typical mistake I always make with mtpl :) 
Is there any help still needed here?

2022-08-16 22:51 UTC, patuwwy commented
yes, should we `si config set log --format json` to use 

SEQ_ID=$(si seq send ./package.tar.gz | jq .id)

or we can just explain `-`

and do

```
si seq send ./package.tar.gz
si seq start - --args [$APIKEY, "BTC", "EUR"]
si inst stdout -
```
btw what is package.tar.gz ? why do i need api key before first steps?

2022-08-18 07:51 UTC, a-tylenda commented
> > yes, should we `si config set log --format json` to use
> > ```
> > SEQ_ID=$(si seq send ./package.tar.gz | jq .id)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or we can just explain `-`
> 
> Thanks for explaining. So I see it as a question of what will be easier to use. Also, if we use consistently in the documentations and samples assigning the result of command to a variable then I would change the default CLI to json (omit the additional step to set the formatting to json). Or modify the documentation everywhere accordingly. I think json is such a standard format for developers that nobody will be scared of it when they see it as default. But maybe I underestimate the --pretty cuteness factor :) @a-tylenda what do you think?

I would stick to CLI. I will propose some changes in a commit ✌🏼

2022-08-18 07:54 UTC, alicja-gruzdz commented
> I would stick to CLI. I will propose some changes in a commit ✌🏼

excellent, thanks!

2022-08-18 10:31 UTC, a-tylenda approved these changes

2022-08-18 11:00 UTC, alicja-gruzdz approved these changes

2022-08-18 11:01 UTC, alicja-gruzdz commented on packages/sth/README.md
> +si inst stdout -
nicely explained

2022-08-18 11:03 UTC, merged