si inst inout
scramjetorg/transform-hub pull request #826
Opened 2023-03-09 17:06 UTC by patuwwy

**What?**  
Added command to `si`:
```
si inst inout <id|-> [-t contentType] [file]       
``` 
Works as `si inst input` + `si inst output` - Allows to send data to Instance input and received data produced on Instance output in one request.

**Why?**  
One request, immediately get output - transformed data for example

**Review checks:**

These aspects need to be checked by the reviewer:

- [ ] Verify and confirm operation (please post a screenshot) 
- [ ] All STH tests pass
- [ ] All [Scramjet Cloud Platform](https://docs.scramjet.org/platform) tests pass
- [ ] Documentation is updated or no changes

2023-03-13 07:18 UTC, ErykSol requested changes
Please add validation for optional arguments thorugh .choices() method

2023-03-13 07:18 UTC, ErykSol commented on packages/cli/src/lib/commands/instance.ts
> +        .option("-t, --content-type <value>", "Content-Type", "text/plain")
should use different API to add type validation (something like): .addOption(new Option(""-t, --content-type <value>", "Content-Type").choices("text/plain"))

2023-03-13 14:30 UTC, patuwwy commented on packages/cli/src/lib/commands/instance.ts
> +        .argument("<id>", "Instance id or '-' for the last one started or selected")
it is consistent with other methods now

2023-03-13 17:18 UTC, ErykSol approved these changes
Looks good :)

2023-03-15 10:02 UTC, a-tylenda commented
verified

![image](https://user-images.githubusercontent.com/61054769/225275717-ada9ca22-07f8-4600-b339-8d6d68ec0bff.png)

2023-03-15 11:28 UTC, merged