si seq delete SEQ_ID --force
scramjetorg/transform-hub pull request #884
Opened 2023-06-15 13:33 UTC by patuwwy

**What?**  
```
DELETE /api/v1/sequence/SEQ_ID
```
Setting HTTP header defined as `HostHeaders.SEQUENCE_FORCE_REMOVE` to `"true"` forces sequence deletion with killing all instances running.

**Why?**  
- [ ] All STH tests pass
- [ ] All [Scramjet Cloud Platform](https://docs.scramjet.org/platform) tests pass
- [ ] Documentation is updated or no changes

2023-06-16 12:16 UTC, ErykSol approved these changes

2023-06-16 14:51 UTC, a-tylenda commented
Option `--force` needs a description:

![image](https://github.com/scramjetorg/transform-hub/assets/61054769/4e1ddb80-8343-4a3d-b656-1c05f7f62bde)

2023-06-16 14:56 UTC, a-tylenda commented
When trying to delete seq with instances (no `--force` option) it returns no info about the running instances, like when I use `si seq prune`, check out the screenshot:
![image](https://github.com/scramjetorg/transform-hub/assets/61054769/bdd0c827-7210-4de7-9da8-7b9dc45a912f)

2023-06-16 14:58 UTC, a-tylenda commented
Besides my comments above the `si seq delete <id> --force` command functionality works as should:
![image](https://github.com/scramjetorg/transform-hub/assets/61054769/d6a0f0f1-b99a-4293-a998-34b804fcd6c7)

2023-06-16 14:59 UTC, a-tylenda requested changes
Please see comments

2023-06-19 14:42 UTC, patuwwy commented
@a-tylenda pls re-check

2023-06-20 10:04 UTC, a-tylenda commented
all good now

![image](https://github.com/scramjetorg/transform-hub/assets/61054769/5ec7488d-439f-42c1-b62f-8552657169ca)

2023-06-20 12:41 UTC, merged