Feat/reconnect
scramjetorg/transform-hub pull request #900
Opened 2023-07-11 09:01 UTC by piotrek6641

**What?**  

**Why?**  

**Usage:**

-
-
-

**Clickup Task:** 

**How it works:**

-
-
-

**Review checks:**

These aspects need to be checked by the reviewer:

- [ ] Verify and confirm operation (please post a screenshot) 
- [ ] All STH tests pass
- [ ] All [Scramjet Cloud Platform](https://docs.scramjet.org/platform) tests pass
- [ ] Documentation is updated or no changes

2023-10-23 13:11 UTC, patuwwy commented
requires changes in Scramjet framework (python) https://github.com/scramjetorg/framework-python/pull/44

2023-12-11 11:57 UTC, alicja-gruzdz commented
Will be released together with
https://github.com/scramjetorg/transform-hub/pull/985
https://github.com/scramjetorg/transform-hub/pull/1002
as they include breaking changes.

2024-01-12 23:46 UTC, kociolekscramjet approved these changes
That's a lot of changes in the core functionalities. But it looks senile :D
No screenshot - everything should work as before but better :)

2024-01-18 09:53 UTC, a-tylenda commented
Bugs fixed within this PR:
- STH Reconnect docker issue](https://app.clickup.com/t/24308805/VDM-1667)
- [STH Reconnect panel ("Instances" tab throws an error)](https://app.clickup.com/t/24308805/VDM-1669)

2024-01-23 14:21 UTC, ErykSolecki requested changes

2024-01-23 14:21 UTC, ErykSolecki commented on packages/adapters/src/kubernetes-instance-adapter.ts
> +            throw Error(RunnerExitCode.PODS_LIMIT_REACHED.toString());
This line probably breaks responses integrity returned from backend.

Check this issue to test response on frontend:
https://github.com/scramjetorg/cloud-platform-panel/issues/524

Old response from server was:
`{"error":"Instance limit reached"}`
Response after changes:
`{"error":"24"}`

2024-03-06 11:53 UTC, a-tylenda approved these changes

2024-03-06 12:21 UTC, merged