Changes in types and messages
scramjetorg/transform-hub pull request #926
Opened 2023-08-07 13:51 UTC by gzukowski

**What?**  
Changes in types and messages.

**Why?**  
There is a need to change the types for "Instance", because of the required content.

**Usage:**

- 
-
-

**Clickup Task:** 

**How it works:**

-
-
-

**Review checks:**

These aspects need to be checked by the reviewer:

- [ ] Verify and confirm operation (please post a screenshot) 
- [ ] All STH tests pass
- [ ] All [Scramjet Cloud Platform](https://docs.scramjet.org/platform) tests pass
- [ ] Documentation is updated or no changes

2023-08-16 10:36 UTC, ErykSol requested changes

2023-08-16 10:36 UTC, ErykSol commented on packages/types/src/rest-api-manager/get-topics.ts
> +        hostId?:string;
Missing fields in response.

2023-08-16 10:36 UTC, ErykSol commented on packages/types/src/instance-store.ts
>      requires?: string,
requires- redundant field? Check if it is used somewhere.

2023-08-16 10:36 UTC, ErykSol commented on packages/types/src/instance-store.ts
> +    ports?: Record<string, number>,
ports- check if needed.

2023-08-16 10:36 UTC, ErykSol commented on packages/types/src/instance-store.ts
>      ended?: Date,
missing field status- check with fronend-team what values are used

2023-08-16 10:36 UTC, ErykSol commented on packages/types/src/rest-api-manager/get-list.ts
> +      tags?: Array<string>,
string[] -cleaner code

2023-08-17 06:16 UTC, ErykSol commented
Missing openApi docs update

2023-08-25 10:33 UTC, ErykSol approved these changes

2023-08-25 10:36 UTC, a-tylenda commented
Merge when openApi docs is done by @gzukowski

2023-08-28 11:56 UTC, merged