Example configs
scramjetorg/transform-hub pull request #968
Opened 2023-10-26 09:23 UTC by a-tylenda

**What?**  
This PR provides a directory with a set of example config files that are used across our software.
This is also a base for documentation, which will be prepared within this click-up task [VDM-1496](https://app.clickup.com/t/24308805/VDM-1496)

**Why?**  

We have quite a number of configs that are used for all kinds of actions like:
- starting STH, 
- starting sequence, 
- work with CLI and profiles,
- etc.

The aim is to have the examples of them all in one place, well described and served to the user. This PR only gathers the example JSON files. The description and usage will be followed within other tasks and PRs. 

**Clickup Task:** 
https://app.clickup.com/t/24308805/VDM-1496

**Review checks:**

These aspects need to be checked by the reviewer:

- [ ] Verify and confirm operation (please post a screenshot) 
- [ ] All STH tests pass
- [ ] All [Scramjet Cloud Platform](https://docs.scramjet.org/platform) tests pass
- [ ] Documentation is updated or no changes

2023-10-27 19:17 UTC, patuwwy commented on configs-examples/sequence-config.json
> +  "limits": 100,
```suggestion
  "limits": {
    "maxMex": 64
  }
```

2023-10-27 19:19 UTC, patuwwy requested changes
see `limits` field in Sequence start config

2023-10-30 07:30 UTC, alicja-gruzdz approved these changes

2023-11-06 18:23 UTC, patuwwy commented
Please wait for #971 and #980. These PRs introduce sequence start config + yaml support in `si seq` commands

2023-11-07 09:50 UTC, patuwwy approved these changes

2023-11-07 09:50 UTC, merged