--env option when starting sth
scramjetorg/transform-hub pull request #986
Opened 2023-11-13 14:09 UTC by piotrek6641

Added option to start declare env variablers when starting sth

#### Example:
`DEVELOPMENT=1 yarn start:dev -e KEY1:VALUE1 KEY2:VALUE2 `

Only acceptable format is providing variables in a key:value format with a space between them.
Otherwise error will be thrown

**Clickup Task:** 
https://app.clickup.com/t/24308805/VDM-1268

2023-11-14 09:45 UTC, patuwwy commented on packages/sth/src/bin/hub.ts
> +    .option("-e, --env <envVars...>", "Array of environment variables")
please rename to --runner-envs and make description more specific

2023-11-14 09:46 UTC, patuwwy commented
Please consider my suggestion from clickup task

2023-11-16 09:00 UTC, patuwwy commented on packages/types/src/sth-configuration.ts
> +    runnerEnvs?: Record<string, string>
```suggestion
    runnerEnvs?: Record<string, string>;
```

2023-11-16 09:10 UTC, patuwwy commented on packages/sth/src/bin/hub.ts
> +    .option("-e, --runner-envs <runnerEnvs>", "Set Runner environmental variables")
```suggestion
    .option("-e, --runner-envs <runnerEnvs>", "Additional ENVs for Runners. e.g ENV1=1;ENV2=2")
```

2023-11-17 10:26 UTC, patuwwy commented on packages/types/src/sth-command-options.ts
> +    monitoringServer: { port: number },
```suggestion
    monitoringServer: { port: number };
```

2023-11-17 10:27 UTC, patuwwy requested changes
see suggestions

2023-11-21 12:22 UTC, patuwwy commented on packages/sth/src/bin/hub.ts
> +    }
```suggestion
    }

```

2023-11-21 12:22 UTC, patuwwy commented on packages/adapters/src/process-instance-adapter.ts
> +            pipesPath: "",
```suggestion
            pipesPath: ""
```

2023-11-21 12:23 UTC, patuwwy commented on packages/adapters/src/kubernetes-instance-adapter.ts
> +        this.sthConfig = sthConfig;
```suggestion
        this.sthConfig = sthConfig;

```

2023-11-21 12:23 UTC, patuwwy commented on packages/adapters/src/docker-instance-adapter.ts
> +            pipesPath: "",
```suggestion
            pipesPath: ""
```

2023-11-21 12:23 UTC, patuwwy requested changes
see formating suggestions

2023-11-23 10:23 UTC, alicja-gruzdz commented
excellent, thanks @piotrek6641 
I have only one comment about naming. Option `-e` maybe confused with `-E` (`--identify-existing`). Perhaps we should leave only `--runner-envs` option. Unless you have an idea how to change these naming to differentiate between them - ?

2023-11-27 11:20 UTC, alicja-gruzdz commented
Verify:
![Screenshot from 2023-11-27 12-14-30](https://github.com/scramjetorg/transform-hub/assets/8177865/09243eb6-bc60-4880-93d9-3691cb980c0c)
Seems to work nicely, thanks!

2023-11-27 11:20 UTC, alicja-gruzdz approved these changes

2023-11-27 11:46 UTC, patuwwy approved these changes

2023-11-27 12:19 UTC, merged