enable formating event structure using query
scramjetorg/transform-hub pull request #987
Opened 2023-11-13 16:26 UTC by piotrek6641

Make events data more readable with removal of redundant data in output
Standard request:
`http://0.0.0.0:8000/api/v1/instance/{instanceId}/events/{eventName}`
returns:
```
{ "eventName": "msg", "message": { "a": 1 } }
{ "eventName": "msg", "message": { "a": 2 } }
{ "eventName": "msg", "message": { "a": 3 } }
```
Requesting with query:
`http://0.0.0.0:8000/api/v1/instance/{instanceId}/events/{eventName}?format=short`
should return:
```
{ "a": 1 }
{ "a": 2 }
{ "a": 3 }
```

**Clickup Task:** 
https://app.clickup.com/t/24308805/VDM-1283

2023-11-13 19:26 UTC, patuwwy commented on packages/types/src/api-expose.ts
> +    query?: { [key: string]: any }};
```suggestion
    query?: { [key: string]: any }
};
```

2023-11-14 15:32 UTC, ErykSol approved these changes

2023-11-14 19:54 UTC, patuwwy requested changes

2023-11-14 19:54 UTC, patuwwy commented on packages/host/src/lib/csi-controller.ts
> +                    out.write(data);
missing return after write

2023-11-14 19:58 UTC, patuwwy commented on packages/host/src/lib/csi-controller.ts
> +                const { _eventName, ...message } = data;
there is no `_eventName` in event message payload so this assignment will cause `message` to be `data`.

2023-11-14 19:59 UTC, patuwwy commented on packages/host/src/lib/csi-controller.ts
> +                out.write(message ? message : {});
pls return just message from data or undefined if message is empty

2023-11-14 20:01 UTC, patuwwy commented on packages/host/src/lib/csi-controller.ts
> +            };
```suggestion
            const handler = (data: any) => {
                if (typeof data !== "object") {
                    out.write(data);
                    return;
                }

                out.write(data.message);
            };
```

2023-11-15 19:46 UTC, patuwwy approved these changes

2023-11-17 10:31 UTC, patuwwy approved these changes

2023-11-27 12:01 UTC, a-tylenda commented
I verified and endpoint `/api/v1/instance/{instanceId}/events/{eventName}` works as described in PR description, but...
there is a discrepancy between API and CLI. This is because under CLI command `si inst event on <id>` there is `getEvent()` method [this.router.get](https://github.com/scramjetorg/transform-hub/blob/feat/events-stream-format/packages/host/src/lib/csi-controller.ts#L713) not [this.router.upstream](https://github.com/scramjetorg/transform-hub/blob/feat/events-stream-format/packages/host/src/lib/csi-controller.ts#L668) edited by @piotrek6641

2023-11-27 14:25 UTC, merged